name: 🐞 Bug Report
description: File a new bug report
title: 'bug: <title>'
body:
  - type: textarea
    attributes:
      label: 'Current Behavior'
      description: 'Describe the problem you are experiencing.  **Please do not paste your logs here.**  Screenshots are welcome.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Expected Behavior'
      description: 'Describe what you expect to happen instead.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Error logs'
      description: | 
        If you have any error logs, please paste itself or a link to Put it in a [Gist](https://gist.github.com) and paste the link.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: 'Reproducibility'
      description: 'Select the reproducibility'
      options:
        - always happens (100%)
        - frequently happens (around 80%)
        - sometimes happens (around 50%)
        - occasionally happens (around 30%)
        - rarely happens (around 10%)
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Minimal Reproducible Example'
      description: |
        It's helpful if you provide a the _smallest, complete code snippet_ that MagicPodAPI client maintainers can run to reproduce the issue. 
    validations:
      required: false
  - type: textarea
    attributes:
      label: 'Environment'
      description: 'Please provide the following information about your environment; feel free to remove any items which are not relevant.'
      value: |
          - Operating system:
          - Last version which did _not_ exhibit the problem (if applicable):
    validations:
      required: false
  - type: textarea
    attributes:
      label: Further Information
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        _Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in._
    validations:
      required: false
